#!/bin/bash

set -e

# Start in dotfiles dir.
BASE_DIR=$(cd $(dirname $0) && echo $PWD)
cd "$BASE_DIR"

echo "Updating submodules..."
git submodule update --init --recursive

# Files and dirs to symlink in HOME for any OS.
FILES=(
  bin
  .ackrc
  .ghci
  .gitconfig
  .gitignore
  .ideavimrc
  .oh-my-zsh
  .path
  .psqlrc
  .style
  .tmux
  .tmux.conf
  .vim
  .vimrc
  .zshrc
)

# Linux-only stuff
if uname | grep -i linux >/dev/null; then
  FILES+=(
    .config/terminator/config
    .IntelliJIdea15/config/colors
    .xbindkeysrc
    .xinitrc
    .Xmodmap
    .xmonad
  )
# Mac-only stuff
elif uname | grep -i darwin >/dev/null; then
  FILES+=(
  )
fi

# Loop through each file in dotfiles and add to HOME.
cd $HOME
for f in "${FILES[@]}"; do
  if [ "$(readlink "$f")" = "$BASE_DIR/$f" ]; then
    # Already symlinked.
    continue;
  fi

  if [ -f "$f" -o -d "$f" ]; then
    >&2 echo "WARNING: '$PWD/$f' already exists, skipping"
    continue;
  fi

  if [ -f "$BASE_DIR/$f" -o -d "$BASE_DIR/$f" ]; then
    echo "Symlinking $BASE_DIR/$f to $HOME/$f"
    (cd "$(dirname $f)" && ln -s "$BASE_DIR/$f")
    continue;
  fi

  >&2 echo "ERROR: '$BASE_DIR/$f' not found!"
  exit 1
done

echo "------------------------"
echo "dotfiles setup complete!"
