#!/bin/bash

set -e

# Start in dotfiles dir.
BASE_DIR=$(cd $(dirname $0) && echo $PWD)
cd "$BASE_DIR"

echo "Updating submodules..."
git submodule update --init --recursive

# Files and dirs to symlink in HOME.
FILES=(
  bin
  .ackrc
  .config/nvim
  .config/terminator/config
  .config/systemd/user/gnome-screensaver.service
  .config/systemd/user/low-battery.service
  .config/systemd/user/low-battery.timer
  .config/systemd/user/notify-osd.service
  .config/systemd/user/nm-applet.service
  .config/systemd/user/stalonetray.service
  .config/systemd/user/xcompmgr.service
  .config/systemd/user/wm.target
  .config/systemd/user/xbindkeys.service
  .ghci
  .gitconfig
  .gitignore
  .ideavimrc
  .IntelliJIdea2017.1
  .npmrc
  .oh-my-zsh
  .path
  .psqlrc
  .style
  .tmux
  .tmux.conf
  .vim
  .vimrc
  .xbindkeysrc
  .xinitrc
  .Xresources
  .Xmodmap
  .xmonad
  .zshrc
)

# Loop through each file in dotfiles and add to HOME.
cd $HOME
for f in "${FILES[@]}"; do
  if [ "$(readlink "$f")" = "$BASE_DIR/$f" ]; then
    # Already symlinked.
    continue;
  fi

  if [ -f "$f" -o -d "$f" ]; then
    >&2 echo "WARNING: '$PWD/$f' already exists, skipping"
    continue;
  fi

  if [ -f "$BASE_DIR/$f" -o -d "$BASE_DIR/$f" ]; then
    echo "Symlinking $BASE_DIR/$f to $HOME/$f"
    (cd "$(dirname $f)" && ln -s "$BASE_DIR/$f")
    continue;
  fi

  >&2 echo "ERROR: '$BASE_DIR/$f' not found!"
  exit 1
done

echo "------------------------"
echo "dotfiles setup complete!"
